lzc-sdk-version: "0.1"
name: iSpy
package: xyz.mxue.ispy
version: 0.0.1
description: ISpy Agent DVR 是一个超级先进的视频监控平台，适用于 Windows，macOS，Linux，Raspberry Pi
  和 **Docker**。这是一个非官方的 Docker 图像代理 DVR 从 iSpy 创建的方便。该软件为要管理的 IP 摄像机创建本地服务器。
homepage: https://github.com/doitandbedone/ispyagentdvr-docker
author: doitandbedone
application:
  subdomain: ispy
  background_task: false
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://ispy.xyz.mxue.ispy.lzcapp:8090/
  ingress:
    - protocol: udp
      port: 3478
      service: ispy
    - protocol: udp
      port: 50000
      service: ispy
services:
  ispy:
    image: registry.lazycat.cloud/mxuexxmy/doitandbedone/ispyagentdvr:4f6e7afbabdcc5bf
    environment:
      - TZ=Asia/Shanghai
    binds:
      - /lzcapp/var/XML:/agent/Media/XML
      - /lzcapp/var/Media:/agent/Media/WebServerRoot/Media
      - /lzcapp/var/Commands:/agent/Commands
